name: Docker Compose CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Compose
      run: docker-compose -f data-engineering/tp-functional-programming-scala/docker-compose.yml up -d

    - name: Wait for environment to be ready
      run: sleep 120

    - name: Execute tests
      run: docker-compose -f data-engineering/tp-functional-programming-scala/docker-compose.yml exec my-scala-app sbt test

    - name: Clean up
      run: docker-compose -f data-engineering/tp-functional-programming-scala/docker-compose.yml down

    - name: Collect logs if needed
      if: failure()  # Only runs if the previous steps fail
      run: docker-compose -f data-engineering/tp-functional-programming-scala/docker-compose.yml logs
